# Generated by Django 4.0.6 on 2022-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('national_num', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], default=1, max_length=15)),
                ('address', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
