# Generated by Django 4.0.5 on 2022-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='sex',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], default=1, max_length=15),
        ),
    ]
